#ifndef INPUT_H
#define INPUT_H

typedef i32 input_key_t;
enum
{
    INPUT_KEY_lmb,
    INPUT_KEY_rmb,
    INPUT_KEY_mmb,
    INPUT_KEY_xb1,
    INPUT_KEY_xb2,
    INPUT_KEY_bspace,
    INPUT_KEY_tab,
    INPUT_KEY_enter,
    INPUT_KEY_shift,
    INPUT_KEY_ctrl,
    INPUT_KEY_alt,
    INPUT_KEY_pause,
    INPUT_KEY_caps,
    INPUT_KEY_esc,
    INPUT_KEY_space,
    INPUT_KEY_pgup,
    INPUT_KEY_pgdn,
    INPUT_KEY_end,
    INPUT_KEY_home,
    INPUT_KEY_left,
    INPUT_KEY_up,
    INPUT_KEY_right,
    INPUT_KEY_down,
    INPUT_KEY_ins,
    INPUT_KEY_del,
    INPUT_KEY_0,
    INPUT_KEY_1,
    INPUT_KEY_2,
    INPUT_KEY_3,
    INPUT_KEY_4,
    INPUT_KEY_5,
    INPUT_KEY_6,
    INPUT_KEY_7,
    INPUT_KEY_8,
    INPUT_KEY_9,
    INPUT_KEY_a,
    INPUT_KEY_b,
    INPUT_KEY_c,
    INPUT_KEY_d,
    INPUT_KEY_e,
    INPUT_KEY_f,
    INPUT_KEY_g,
    INPUT_KEY_h,
    INPUT_KEY_i,
    INPUT_KEY_j,
    INPUT_KEY_k,
    INPUT_KEY_l,
    INPUT_KEY_m,
    INPUT_KEY_n,
    INPUT_KEY_o,
    INPUT_KEY_p,
    INPUT_KEY_q,
    INPUT_KEY_r,
    INPUT_KEY_s,
    INPUT_KEY_t,
    INPUT_KEY_u,
    INPUT_KEY_v,
    INPUT_KEY_w,
    INPUT_KEY_x,
    INPUT_KEY_y,
    INPUT_KEY_z,
    INPUT_KEY_numpad_0,
    INPUT_KEY_numpad_1,
    INPUT_KEY_numpad_2,
    INPUT_KEY_numpad_3,
    INPUT_KEY_numpad_4,
    INPUT_KEY_numpad_5,
    INPUT_KEY_numpad_6,
    INPUT_KEY_numpad_7,
    INPUT_KEY_numpad_8,
    INPUT_KEY_numpad_9,
    INPUT_KEY_mul,
    INPUT_KEY_add,
    INPUT_KEY_separator,
    INPUT_KEY_sub,
    INPUT_KEY_decimal,
    INPUT_KEY_div,
    INPUT_KEY_f1,
    INPUT_KEY_f2,
    INPUT_KEY_f3,
    INPUT_KEY_f4,
    INPUT_KEY_f5,
    INPUT_KEY_f6,
    INPUT_KEY_f7,
    INPUT_KEY_f8,
    INPUT_KEY_f9,
    INPUT_KEY_f10,
    INPUT_KEY_f11,
    INPUT_KEY_f12,
    INPUT_KEY_f13,
    INPUT_KEY_f14,
    INPUT_KEY_f15,
    INPUT_KEY_f16,
    INPUT_KEY_f17,
    INPUT_KEY_f18,
    INPUT_KEY_f19,
    INPUT_KEY_f20,
    INPUT_KEY_f21,
    INPUT_KEY_f22,
    INPUT_KEY_f23,
    INPUT_KEY_f24,
    INPUT_KEY_numlck,
    INPUT_KEY_scrlck,
    INPUT_KEY_lshift,
    INPUT_KEY_rshift,
    INPUT_KEY_lctrl,
    INPUT_KEY_rctrl,
    INPUT_KEY_lalt,
    INPUT_KEY_ralt,
    INPUT_KEY_colon,
    INPUT_KEY_plus,
    INPUT_KEY_comma,
    INPUT_KEY_minus,
    INPUT_KEY_period,
    INPUT_KEY_fslash,
    INPUT_KEY_tilde,
    INPUT_KEY_lbrace,
    INPUT_KEY_bslash,
    INPUT_KEY_rbrace,
    INPUT_KEY_quote,
    INPUT_KEY_count
};

typedef struct input_state_t input_state_t;
struct input_state_t
{
    vec2_t mouse_pos;
    vec2_t mouse_scroll;
    i8     keys[INPUT_KEY_count];
};

global input_state_t g_input_state = {0};

#endif // INPUT_H
